/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversation/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Exchange
         * @description Remember one moment: what was said, how the user felt, what they replied.
         */
        post: operations["log_exchange_api_conversation_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversation/memory/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Memory */
        get: operations["get_memory_api_conversation_memory__user_id__get"];
        put?: never;
        post?: never;
        /** Forget */
        delete: operations["forget_api_conversation_memory__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emotion/model/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model */
        get: operations["get_model_api_emotion_model__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emotion/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Samples */
        post: operations["add_samples_api_emotion_samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/emotion/train": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Train */
        post: operations["train_api_emotion_train_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Expand
         * @description First-letter typing: "iww" -> "I want water" (using the conversation and the memory).
         */
        post: operations["expand_api_expand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Feedback */
        post: operations["add_feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description The saved profile, or an empty one with the default quick phrases.
         */
        get: operations["get_profile_api_profile__user_id__get"];
        /** Put Profile */
        put: operations["put_profile_api_profile__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Related
         * @description Is speech heard while replies were loading part of the same turn? (fast model)
         */
        post: operations["related_api_related_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggestions */
        post: operations["suggestions_api_suggestions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clone Voice */
        post: operations["clone_voice_api_voice_clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_voice_profile__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Voice */
        post: operations["select_voice_api_voice_select_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/voice/speak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Speak */
        post: operations["speak_api_voice_speak_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_clone_voice_api_voice_clone_post */
        Body_clone_voice_api_voice_clone_post: {
            /** Duration */
            duration?: number | null;
            /** File */
            file: string;
            /** Name */
            name: string;
            /**
             * User Id
             * @default local-user
             */
            user_id: string;
        };
        /**
         * ConversationEmotion
         * @description How this moment feels, judged from the partner's words AND the user's face.
         */
        ConversationEmotion: {
            /** Confidence */
            confidence: number;
            /**
             * Emotion
             * @enum {string}
             */
            emotion: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /**
             * Reason
             * @description Short: why (and any words/face disagreement)
             * @default
             */
            reason: string;
            /**
             * Source
             * @default face + words
             * @enum {string}
             */
            source: "face" | "words" | "face + words";
        };
        /** ConversationTurn */
        ConversationTurn: {
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "partner" | "user";
            /** Text */
            text: string;
        };
        /**
         * EmotionModel
         * @description A trained logistic-regression model, exported so the browser can run it locally.
         *
         *     Prediction in the browser:
         *         x_scaled = (x - means) / scales
         *         logits[c] = sum_j(coef[c][j] * x_scaled[j]) + intercept[c]
         *         probabilities = softmax(logits)
         */
        EmotionModel: {
            /**
             * Accuracy
             * @description Average per-emotion accuracy on held-out recordings
             */
            accuracy?: number | null;
            /**
             * Advice
             * @description e.g. "sad needs more examples (record it again)"
             */
            advice?: string[];
            /** Classes */
            classes: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious")[];
            /**
             * Coef
             * @description shape: [len(classes)][len(feature_names)]
             */
            coef: number[][];
            /** Feature Names */
            feature_names: string[];
            /** Intercept */
            intercept: number[];
            /** Means */
            means: number[];
            /** N Samples */
            n_samples: number;
            /** Per Class Accuracy */
            per_class_accuracy?: {
                [key: string]: number;
            };
            /** Scales */
            scales: number[];
            /** User Id */
            user_id: string;
        };
        /** EmotionSample */
        EmotionSample: {
            /**
             * Features
             * @description Same order as `feature_names` in the request
             */
            features: number[];
            /**
             * Label
             * @enum {string}
             */
            label: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /**
             * Source
             * @default calibration
             * @enum {string}
             */
            source: "calibration" | "feedback";
        };
        /**
         * ExchangeLog
         * @description One moment of conversation, logged when a reply is spoken.
         */
        ExchangeLog: {
            /**
             * Detected Emotion
             * @description What the user's face showed right after the partner spoke
             */
            detected_emotion?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /** Emotion Confidence */
            emotion_confidence?: number | null;
            /**
             * Mood
             * @description The user's mood setting
             */
            mood?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /**
             * Partner Text
             * @description What the partner had just said
             */
            partner_text: string;
            /** Reply Text */
            reply_text: string;
            /**
             * Reply Tone
             * @enum {string}
             */
            reply_tone: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /**
             * User Id
             * @default local-user
             */
            user_id: string;
            /** Utterance Id */
            utterance_id: string;
        };
        /**
         * ExpandRequest
         * @description First-letter typing: guess the sentence from the first letter of each word.
         */
        ExpandRequest: {
            /** History */
            history?: components["schemas"]["ConversationTurn"][];
            /**
             * Initials
             * @description e.g. "iww" for "I want water"
             */
            initials: string;
            /** Mood */
            mood?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            profile?: components["schemas"]["UserProfile"] | null;
            /**
             * User Id
             * @default local-user
             */
            user_id: string;
        };
        /**
         * FaceReaction
         * @description The user's face while reacting to what was just said (not just one label).
         */
        FaceReaction: {
            /**
             * Confidence
             * @description How sure the peak was
             * @default 0
             */
            confidence: number;
            /**
             * Peak
             * @description Strongest non-neutral expression
             */
            peak?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /**
             * Scores
             * @description Share of the reaction window per emotion, weighted by confidence (0..1)
             */
            scores?: {
                [key: string]: number;
            };
        };
        /**
         * FeedbackRequest
         * @description One piece of feedback about a spoken reply.
         *
         *     The user's eye yes/no and the partner's tap arrive at different moments, so both
         *     fields are optional; send whichever one you have. `utterance_id` ties them together.
         */
        FeedbackRequest: {
            /**
             * Feature Frames
             * @description Face features from the reaction window (about 10 frames); preferred
             */
            feature_frames?: number[][] | null;
            /** Feature Names */
            feature_names?: string[] | null;
            /**
             * Features
             * @description Face-feature snapshot taken when the tone was suggested
             */
            features?: number[] | null;
            /** Partner Reaction */
            partner_reaction?: ("understood" | "seemed_off") | null;
            /** Reply Text */
            reply_text: string;
            /**
             * Spoken Tone
             * @enum {string}
             */
            spoken_tone: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /** User Id */
            user_id: string;
            /**
             * User Tone Ok
             * @description User's eye yes/no
             */
            user_tone_ok?: boolean | null;
            /** Utterance Id */
            utterance_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryEntry */
        MemoryEntry: {
            /** Created At */
            created_at: string;
            /** Detected Emotion */
            detected_emotion: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /** Partner Text */
            partner_text: string;
            /** Reply Text */
            reply_text: string;
            /**
             * Reply Tone
             * @enum {string}
             */
            reply_tone: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /** Tone Ok */
            tone_ok: boolean | null;
        };
        /** MemoryResponse */
        MemoryResponse: {
            /** Count */
            count: number;
            /**
             * Entries
             * @description Newest first
             */
            entries: components["schemas"]["MemoryEntry"][];
        };
        /** RelatedRequest */
        RelatedRequest: {
            /**
             * New
             * @description Speech heard while the replies were being prepared
             */
            new: string;
            /**
             * Previous
             * @description What the partner said this turn so far
             */
            previous: string;
        };
        /** RelatedResponse */
        RelatedResponse: {
            /**
             * Related
             * @description True if the new speech continues the same turn
             */
            related: boolean;
        };
        /** SamplesRequest */
        SamplesRequest: {
            /** Feature Names */
            feature_names: string[];
            /** Samples */
            samples: components["schemas"]["EmotionSample"][];
            /** User Id */
            user_id: string;
        };
        /** SelectVoiceRequest */
        SelectVoiceRequest: {
            /** Name */
            name?: string | null;
            /**
             * User Id
             * @default local-user
             */
            user_id: string;
            /** Voice Id */
            voice_id: string;
        };
        /** SpeakRequest */
        SpeakRequest: {
            /**
             * Emotion
             * @default neutral
             * @enum {string}
             */
            emotion: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
            /** Text */
            text: string;
            /**
             * User Id
             * @default local-user
             */
            user_id: string;
            /** Voice Id */
            voice_id?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            /** Id */
            id: string;
            /**
             * Text
             * @description A short reply the user could say, in first person
             */
            text: string;
            /**
             * Tone
             * @description The emotional tone this reply is best spoken with
             * @enum {string}
             */
            tone: "neutral" | "happy" | "sad" | "excited" | "joking" | "serious";
        };
        /** SuggestionsRequest */
        SuggestionsRequest: {
            /** @description The full face reading behind `reaction` */
            face_reaction?: components["schemas"]["FaceReaction"] | null;
            /**
             * History
             * @description Oldest first; last turn is usually the partner
             */
            history: components["schemas"]["ConversationTurn"][];
            /**
             * Mood
             * @description The user's persistent mood setting, if any
             */
            mood?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /** @description Who the user is, so replies feel personal */
            profile?: components["schemas"]["UserProfile"] | null;
            /**
             * Reaction
             * @description The user's immediate emotional reaction / facial expression to what was said
             */
            reaction?: ("neutral" | "happy" | "sad" | "excited" | "joking" | "serious") | null;
            /**
             * User Id
             * @description Whose conversation memory to use
             * @default local-user
             */
            user_id: string;
        };
        /** SuggestionsResponse */
        SuggestionsResponse: {
            conversation_emotion?: components["schemas"]["ConversationEmotion"] | null;
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** TrainRequest */
        TrainRequest: {
            /** User Id */
            user_id: string;
        };
        /**
         * UserProfile
         * @description Optional info that makes suggestions feel personal, plus the quick-access phrases.
         */
        UserProfile: {
            /**
             * Common Needs
             * @description e.g. "water", "pillow"
             */
            common_needs?: string[];
            /** Interests */
            interests?: string[];
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Phrases
             * @description Quick-access phrases
             */
            phrases?: string[];
            /**
             * Relationships
             * @description e.g. "daughter Maya"
             */
            relationships?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VoiceItem */
        VoiceItem: {
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Name */
            name: string;
            /** Voice Id */
            voice_id: string;
        };
        /** VoiceProfileResponse */
        VoiceProfileResponse: {
            /** Configured */
            configured: boolean;
            /** Name */
            name: string | null;
            /** User Id */
            user_id: string;
            /** Voice Id */
            voice_id: string | null;
            /**
             * Voices
             * @default []
             */
            voices: components["schemas"]["VoiceItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    log_exchange_api_conversation_log_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExchangeLog"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memory_api_conversation_memory__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_api_conversation_memory__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_api_emotion_model__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_samples_api_emotion_samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SamplesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    train_api_emotion_train_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmotionModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_api_expand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_profile_api_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_profile_api_profile__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_api_related_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelatedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggestions_api_suggestions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_voice_api_voice_clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_clone_voice_api_voice_clone_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_voice_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_voice_api_voice_select_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectVoiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    speak_api_voice_speak_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
